In [1]:
import numpy as np

In [3]:
#crear una array de dos dimenciones apartir de listas
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr, type(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


In [5]:
#crear arreglo de ceros con forma de (3,4)
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
# matriz identidad

arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
# arreglo 3D
# 2 arrelgos de 3,4

arr = np.zeros((2,4,4)) # primer dijito la cantidad. los otros dos las dimenciones
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

OPERACIONES MATEMATICAS Y ESTADISTICAS


- promedio = mean
- suma = sum
- mediana = median
- producto = prod
- desviacion = std
- varianza = var
- minimo = min
- maximo = max
- suma acumulada = cumsum
- suma de elementos = ej: array + array ...
- resta = -
- multiplicaicon = *
- division = /


In [17]:
#Operaciones Matematicas y Estadisticas

# calcular la suma de elementos
suma = np.sum(arr)
suma

0.0